alias neo=neofetch
alias py=python3
alias py2=python2
alias ping="ping -c10 1.1.1.1"
alias update="sudo apt update"
alias upgrade="sudo apt upgrade"
alias install="sudo apt install"
alias search="sudo apt search"
alias remove="sudo apt remove"
alias autoremove="sudo apt autoremove"
alias autoclean="sudo apt autoclean"
alias wget="wget -P /home/natalie/Downloads/"
